on:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ramiro
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  

    - name: Build
      uses: okteto/actions/build@v1
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        tag: ramiro/slack-stargazer:${{ github.sha }}

    - name: Get Kubeconfig
      uses: okteto/actions/namespace@v1
      id: namespace
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: actions-rberrelleza
    
    - name: Deploy and Wait
      uses: okteto/actions/deploy@v1
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}  
      with:
        namespace: stargazer-rberrelleza
        manifest: k8s.yml
        tag: ramiro/slack-stargazer:${{ github.sha }}
        waitOn: deployment/slack-stargazer
    
    - name: Verify
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://slack-stargazer-stargazer-rberrelleza.cloud.okteto.net"
        expected-statuses: "200"